# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
    silent: false
  dev:tsp:
    desc: Typespec compile
    cmd: tsp compile ./tsp-files
    silent: true
  up:
    desc: Docker compose up -d
    cmd: docker-compose up -d
    silent: false
  down:
    desc: Docker compose down
    cmd: docker-compose down
    silent: false
